- build.gradle
- src/main/java/com/windmeal/global/configuration/WebConfig.java
- src/main/java/com/windmeal/global/configuration/database/DataSourceKey.java
- src/main/java/com/windmeal/global/configuration/database/ReplicationDataSourceConfig.java
- src/main/java/com/windmeal/global/configuration/database/ReplicationRoutingDataSource.java
- src/main/java/com/windmeal/store/controller/TestController.java
- src/main/java/com/windmeal/store/domain/Store.java
- src/main/java/com/windmeal/store/repository/StoreRepository.java
- src/main/java/com/windmeal/store/service/StoreService.java
- @Transactional(readOnly = true) 설정이 되어 있는 경우 slave DB 로 요청, 그외 요청의 경우 master DB 로 요청 되도록 설정 추가
> Feat: mysql 2중화를 위한 환경설정 추가

- build.gradle
- src/main/java/com/windmeal/global/configuration/database/RedisRepositoryConfig.java
> Feat: redis 환경설정 및 패키지 추가

- src/main/java/com/windmeal/generic/domain/Money.java
- src/main/java/com/windmeal/global/configuration/database/QueryDslConfig.java
- src/main/java/com/windmeal/store/controller/CategoryController.java
- src/main/java/com/windmeal/store/controller/MenuController.java
- src/main/java/com/windmeal/store/controller/StoreController.java
- src/main/java/com/windmeal/store/domain/Menu.java
- src/main/java/com/windmeal/store/dto/request/MenuCreateRequest.java
- src/main/java/com/windmeal/store/dto/request/OptionCreateRequest.java
- src/main/java/com/windmeal/store/dto/request/StoreCreateRequest.java
- src/main/java/com/windmeal/store/dto/response/MenuCategoryResponse.java
- src/main/java/com/windmeal/store/dto/response/MenuResponse.java
- src/main/java/com/windmeal/store/dto/response/StoreMenuResponse.java
- src/main/java/com/windmeal/store/repository/MenuCategoryJpaRepository.java
- src/main/java/com/windmeal/store/repository/MenuJpaRepository.java
- src/main/java/com/windmeal/store/repository/MenuRepository.java
- src/main/java/com/windmeal/store/repository/MenuRepositoryImpl.java
- src/main/java/com/windmeal/store/repository/OptionSpecificationJpaRepository.java
- src/main/java/com/windmeal/store/repository/StoreCategoryRepositoryImpl.java
- src/main/java/com/windmeal/store/service/MenuCategoryService.java
- src/main/java/com/windmeal/store/service/MenuService.java
- src/main/java/com/windmeal/store/service/StoreService.java
- src/test/java/com/windmeal/store/repository/CategoryRepositoryImplTest.java
- src/test/java/com/windmeal/store/repository/OptionRepositoryImplTest.java
- src/test/java/com/windmeal/store/repository/StoreCategoryRepositoryImplTest.java
- src/test/java/com/windmeal/store/service/CategoryServiceTest.java
- src/test/java/com/windmeal/store/service/MenuCategoryServiceTest.java
- src/test/java/com/windmeal/store/service/MenuServiceTest.java
- src/test/java/com/windmeal/store/service/StoreServiceTest.java
- src/test/java/com/windmeal/store/validator/StoreValidatorTest.java
> Test: 테스트 코드 @Transactinal 제거 및 teardown 추가

- src/main/java/com/windmeal/order/domain/Order.java
- src/main/java/com/windmeal/order/domain/OrderMenu.java
- src/main/java/com/windmeal/order/domain/OrderMenuOptionGroup.java
- src/main/java/com/windmeal/store/controller/OptionController.java
- src/main/java/com/windmeal/store/controller/StoreController.java
- src/main/java/com/windmeal/store/domain/Menu.java
- src/main/java/com/windmeal/store/domain/OptionGroup.java
- src/main/java/com/windmeal/store/dto/request/MenuCategoryCreateRequest.java
- src/main/java/com/windmeal/store/dto/request/MenuCategoryUpdateRequest.java
- src/main/java/com/windmeal/store/dto/request/MenuCreateRequest.java
- src/main/java/com/windmeal/store/dto/request/OptionCreateRequest.java
- src/main/java/com/windmeal/store/dto/request/StoreCreateRequest.java
- src/main/java/com/windmeal/store/dto/request/StoreUpdateRequest.java
- src/main/java/com/windmeal/store/dto/response/MenuCategoryResponse.java
- src/main/java/com/windmeal/store/dto/response/MenuOptionResponse.java
- src/main/java/com/windmeal/store/dto/response/MenuResponse.java
- src/main/java/com/windmeal/store/dto/response/OptionGroupResponse.java
- src/main/java/com/windmeal/store/dto/response/OptionSpecResponse.java
- src/main/java/com/windmeal/store/dto/response/StoreMenuResponse.java
- src/main/java/com/windmeal/store/dto/response/StoreResponse.java
> swagger 문서화를 위한 코드 추가

- src/main/java/com/windmeal/store/controller/MenuController.java
> Refactor :  swagger 코드 추가

- build.gradle
- src/main/java/com/windmeal/generic/domain/Money.java
- src/main/java/com/windmeal/generic/domain/MoneyDeserializer.java
- src/main/java/com/windmeal/member/domain/Member.java
- src/main/java/com/windmeal/member/domain/MemberBase.java
- src/main/java/com/windmeal/order/controller/OrderController.java
- src/main/java/com/windmeal/order/domain/Order.java
- src/main/java/com/windmeal/order/domain/OrderMenu.java
- src/main/java/com/windmeal/order/domain/OrderMenuOptionGroup.java
- src/main/java/com/windmeal/order/domain/OrderMenuOptionSpecification.java
- src/main/java/com/windmeal/order/dto/OrderCreateRequest.java
- src/main/java/com/windmeal/order/mapper/OrderRequestMapper.java
- src/main/java/com/windmeal/order/repository/OrderRepository.java
- src/main/java/com/windmeal/order/service/OrderService.java
- src/main/java/com/windmeal/order/validator/OrderValidator.java
- src/main/java/com/windmeal/store/controller/StoreController.java
- src/main/java/com/windmeal/store/domain/Menu.java
- src/main/java/com/windmeal/store/domain/OptionGroup.java
- src/main/java/com/windmeal/store/domain/OptionSpecification.java
- src/main/java/com/windmeal/store/domain/Store.java
- src/test/java/com/windmeal/generic/domain/MoneyTest.java
- src/test/java/com/windmeal/order/repository/OrderRepositoryTest.java
- src/test/java/com/windmeal/order/service/OrderServiceTest.java
- src/test/java/com/windmeal/store/repository/OptionSpecificationRepositoryTest.java
- src/test/java/com/windmeal/store/service/MenuServiceTest.java
- bulk 연산 수행을 위한 @GeneratedValue Identity -> Sequence 변경
- OrderRequestMapper 작성
- 추후 총 금액 계산 로직 작성 예정
ex)
> Feat : order 저장 로직 작성

- src/main/java/com/windmeal/global/configuration/WebConfig.java
- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
- src/main/java/com/windmeal/global/util/CookieUtil.java
ex)
- 최상단 cors 필터 추가, 테스트 위한 merge
> Feat : 최상단 Cors 필터 추가

- src/main/java/com/windmeal/global/security/handler/CustomFailureHandler.java
- src/main/java/com/windmeal/global/security/handler/CustomSuccessHandler.java
- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
- src/main/java/com/windmeal/global/security/impl/filter/JwtAuthenticationFilter.java
- src/main/java/com/windmeal/global/security/oauth2/impl/CustomOAuth2UserService.java
- src/main/java/com/windmeal/global/token/security/JwtAuthenticationEntryPoint.java
> !HOTFIX : 쿠키 드롭관련 추적을 위한 로그 추가

- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
- src/main/java/com/windmeal/global/security/impl/filter/JwtAuthenticationFilter.java
> !HOTFIX : request 관련 구체적인 로그 추가

- src/main/java/com/windmeal/global/configuration/WebConfig.java
- src/main/java/com/windmeal/global/token/security/JwtAuthenticationEntryPoint.java
- JwtAuthenticationEntryPoint 로그 추가, Origin 추가
> !HOTFIX : 오리진 추가, entryPoint 로그 추가

- src/main/java/com/windmeal/global/configuration/WebConfig.java
- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
> !HOTFIX : 임시적 Origin, header 전체 허용

- src/main/java/com/windmeal/global/configuration/WebConfig.java
- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
- src/main/java/com/windmeal/global/token/security/JwtAuthenticationEntryPoint.java
> Auth security

- src/main/java/com/windmeal/global/security/impl/filter/JwtAuthenticationFilter.java
- authentication filter 에서 암호화를 추가하며 발생한 오류 수정
> !HOTFIX : swagger 오류 수정

- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
> !refactor : cors 필터 주석

- src/main/java/com/windmeal/global/security/impl/filter/JwtAuthenticationFilter.java
> refactor : response header 관련 filter 수정

- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
- src/main/java/com/windmeal/global/security/impl/filter/JwtAuthenticationFilter.java
> refactor : cors 필터 복구, 코드 수정

- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
> refactor : cors 필터 수정 - response 헤더 오리진

- src/main/java/com/windmeal/member/controller/MemberController.java
> refactor : 닉네임 중복 관련 api 치명적인 로직 오류 수정

- .github/workflows/was1.yml
- .github/workflows/was2.yml
- WAS간 기능 동작 불일치 문제 해결을 위한 CICD 스크립트 변경
> Actions 스크립트 수정

- src/main/java/com/windmeal/member/service/MemberService.java
> !HOTFIX : was 동작 차이 원인 추적을 위한 로그 추가

- src/main/java/com/windmeal/member/controller/MemberController.java
> refactor : 닉네임 중복 api 반환 결과 변경

- src/main/java/com/windmeal/member/controller/AuthController.java
> refactor : 토큰 재발급 스웨거 정보 추가

- src/main/java/com/windmeal/global/constants/SecurityConstants.java
- src/main/java/com/windmeal/global/security/handler/CustomSuccessHandler.java
- src/main/java/com/windmeal/global/token/util/TokenProvider.java
- src/main/java/com/windmeal/member/controller/MemberController.java
- src/main/java/com/windmeal/member/service/MemberService.java
- 토큰 클레임에 사용자 정보 추가 (d72c3d678314cde6a64b9a07b26f3ec999f3e217)
- 스웨거 정보 추가 (f7373cf44d32796109224485905c7407a8621ed9)
> 토큰 클레임 정보 수정

- src/main/java/com/windmeal/WindmealApplication.java
- src/main/java/com/windmeal/model/event/Event.java
- src/main/java/com/windmeal/model/event/EventConfig.java
- src/main/java/com/windmeal/model/event/EventPublisher.java
- src/main/java/com/windmeal/model/event/FCMEvent.java
- src/main/java/com/windmeal/model/event/TestDeliveryCancelEventHandler.java
- src/main/java/com/windmeal/order/domain/Order.java
- src/main/java/com/windmeal/order/domain/OrderCancel.java
- src/main/java/com/windmeal/order/domain/event/DeliveryCancelEvent.java
- src/main/java/com/windmeal/order/domain/event/DeliveryMatchEvent.java
- src/main/java/com/windmeal/order/repository/DeliveryCustomRepositoryImpl.java
- src/main/java/com/windmeal/order/service/DeliveryService.java
ex)
- 알람 로직 수행을 위한 event 구축
- 내가 요청한 배달, 내가 배달중인 주문 리스트 조회 쿼리 수정
> Order develop

- src/main/java/com/windmeal/order/controller/DeliveryController.java
- src/main/java/com/windmeal/order/controller/OrderController.java
- src/main/java/com/windmeal/order/dto/request/DeliveryCreateRequest.java
- src/main/java/com/windmeal/order/dto/response/OwnDeliveryListResponse.java
- src/main/java/com/windmeal/order/dto/response/OwnOrderListResponse.java
- src/main/java/com/windmeal/order/repository/delivery/DeliveryCustomRepository.java
- src/main/java/com/windmeal/order/repository/delivery/DeliveryCustomRepositoryImpl.java
- src/main/java/com/windmeal/order/repository/order/OrderCustomRepository.java
- src/main/java/com/windmeal/order/repository/order/OrderCustomRepositoryImpl.java
- src/main/java/com/windmeal/order/service/DeliveryService.java
- src/main/java/com/windmeal/order/service/OrderService.java
- src/main/java/com/windmeal/store/controller/StoreController.java
- src/main/java/com/windmeal/store/dto/request/StoreCategoryCreateRequest.java
- src/main/java/com/windmeal/store/dto/response/CategoryStoreMenuResponse.java
- src/main/java/com/windmeal/store/dto/response/StoreCategoryResponse.java
- src/main/java/com/windmeal/store/exception/StoreCategoryNotFoundException.java
- src/main/java/com/windmeal/store/repository/StoreCategoryCustomRepository.java
- src/main/java/com/windmeal/store/repository/StoreCategoryCustomRepositoryImpl.java
- src/main/java/com/windmeal/store/service/StoreService.java
- src/test/java/com/windmeal/Fixtures.java
- src/test/java/com/windmeal/order/repository/DeliveryRepositoryTest.java
- src/test/java/com/windmeal/order/repository/OrderRepositoryTest.java
ex)
- 내가 주문했던 목록 조회 구현 - slice
- 내가 주문해서 그동안 아낀 금액 조회 구현
- 내가 배달했던 목록 조회 구현 - slice
- 내가 배달해서 그동안 벌어들인 금액 조회 구현
> Feat : 마이페이지 - 내가 주문했던 목록 조회, 내가 배달했던 목록 조회 구현

- src/main/java/com/windmeal/store/service/OptionService.java
> Refactor : dto 네이밍 변경

- .github/workflows/was1.yml
- .github/workflows/was2.yml
> Refactor : firebase config 관련 설정 추가

- .github/workflows/was1.yml
- .github/workflows/was2.yml
> Refactor : 깃허브 yml 수정

- .github/workflows/was1.yml
- .github/workflows/was2.yml
> Refactor : firebase 관련 yml 수정

- src/main/java/com/windmeal/chat/domain/ChatroomDocument.java
> Feat : 채팅방 필드 수정 - 마지막 메시지 필드 추가

- src/main/java/com/windmeal/alarm/service/FcmNotificationService.java
- src/main/java/com/windmeal/global/configuration/FcmConfig.java
- src/main/java/com/windmeal/member/controller/MemberReportController.java
- src/main/java/com/windmeal/member/domain/MemberReport.java
- src/main/java/com/windmeal/member/dto/request/MemberReportCreateRequest.java
- src/main/java/com/windmeal/member/dto/response/MemberReportListResponse.java
- src/main/java/com/windmeal/member/repository/MemberReportCustomRepository.java
- src/main/java/com/windmeal/member/repository/MemberReportCustomRepositoryImpl.java
- src/main/java/com/windmeal/member/repository/MemberReportRepository.java
- src/main/java/com/windmeal/member/service/MemberReportService.java
- src/main/java/com/windmeal/report/controller/ReportController.java
- src/main/java/com/windmeal/report/repository/ReportCustomRepository.java
- src/main/java/com/windmeal/report/repository/ReportCustomRepositoryImpl.java
- src/main/java/com/windmeal/report/service/ReportService.java
> 멤버 신고 기능 구현 및 건의 기능 수정

- src/main/java/com/windmeal/chat/domain/ChatroomDocument.java
- src/main/java/com/windmeal/global/security/handler/CustomFailureHandler.java
- 채팅방 필드 수정 (19db85210a23846bb34c429c39e5fc553faab339)
- 에러 메시지 인코딩 오류 수정(e868f7c4c260d777461521adde5ad3b6e5a26000)
> 에러 메시지 인코딩 오류 수정

- src/main/java/com/windmeal/global/security/handler/CustomFailureHandler.java
- src/main/java/com/windmeal/global/token/security/JwtAuthenticationEntryPoint.java
> Refactor : 에러 메시지 인코딩 오류 수정

- src/main/java/com/windmeal/alarm/service/FcmNotificationService.java
- src/main/java/com/windmeal/global/configuration/FcmConfig.java
> Refactor : fcm

- src/main/java/com/windmeal/alarm/service/FcmNotificationService.java
- src/main/java/com/windmeal/global/configuration/FcmConfig.java
- src/main/java/com/windmeal/global/configuration/security/SecurityConfig.java
> Refactor : 권한 수정, fcm 원상복구

- src/main/java/com/windmeal/global/configuration/security/SecurityConfig.java
> Refactor : 권한 원상복구

- src/main/java/com/windmeal/global/security/impl/filter/JwtAuthenticationFilter.java
- src/main/java/com/windmeal/member/controller/MemberController.java
- src/main/java/com/windmeal/member/domain/event/AlarmTestEvent.java
- src/main/java/com/windmeal/member/service/MemberService.java
- src/main/java/com/windmeal/model/event/FCMEventHandler.java
- pwa 알람 테스트용 API 작성 (81836a68450096e60c9713183ffd618578140e57)
> Feat : 프론트엔드 알람 테스트용 API 작성

- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
- CustomCorsFilter에서 발생한 Bean Injection 오류 수정
- Bean 생성 전 AutowiredAnnotationBeanPostProcessor 활용을 시도해서 발생
> Fix : Cors 필터 Bean Injection 오류 수정

- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
- Bean Injection 관련 오류 조치가 잘못됐음
- 수정된 yml이 반영되지 않아서 발생했던 오류를 다른 오류와 혼동하여 잘못된 조치 취함.
> Fix : 원상복귀

- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
- corsFilter 오리진 헤더 수정
-  2개 이상의 헤더를 이어서 사용하는 실수를 범했음. 수정함.
> Fix : corsFilter 오리진 헤더 수정

- src/main/java/com/windmeal/member/controller/MemberController.java
> Fix : 오타수정

- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
> Fix : 허용 오리진 수정

- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
- src/main/java/com/windmeal/model/event/FCMEventHandler.java
> Refactor : 허용 오리진 수정 - 로컬

- src/main/java/com/windmeal/global/constants/JwtConstants.java
- src/main/java/com/windmeal/member/controller/MemberController.java
- src/main/java/com/windmeal/member/dto/request/MemberInfoRequest.java
- src/main/java/com/windmeal/member/dto/request/NicknameRequest.java
- src/main/java/com/windmeal/member/service/BlackListService.java
- src/main/java/com/windmeal/member/service/MemberService.java
- src/test/java/com/windmeal/IntegrationTest.java
- src/test/java/com/windmeal/member/service/MemberServiceTest.java
- src/test/java/com/windmeal/store/service/OptionServiceTest.java
- Member API 테스트 코드 작성(d986023b0b6d358168324fbc8666a89f54f747e0)
- 코드 작성 과정에서 프로덕션 코드 리팩토링(08a74edb033fc740964d8320fa6f1c0b3daf32e5)
- 프론트엔드의 요청으로 인한 토큰 만료 시간 임의 조정
> 테스트 코드 작성, 토큰 만료 시간 임의 조정

- src/main/java/com/windmeal/member/service/AuthService.java
- 리이슈 오류 관련 로그 추가 (5ec1896edeb6b4fb6d70df013abb40a7a1865916)
> 리이슈 오류 관련 로그 추가

- src/main/java/com/windmeal/global/constants/JwtConstants.java
- 토큰 갱신 기간 원위치 (9553b88f79a76b842288ba2a51db23595ad447eb)
> 토큰 갱신 기간 원위치

- src/main/java/com/windmeal/chat/service/ChatRoomService.java
- src/test/java/com/windmeal/annotation/ControllerTest.java
- src/test/java/com/windmeal/annotation/IntegrationTest.java
- src/test/java/com/windmeal/annotation/WithMockCustomUser.java
- src/test/java/com/windmeal/annotation/WithMockCustomUserSecurityContextFactory.java
- src/test/java/com/windmeal/member/service/MemberControllerTest.java
- src/test/java/com/windmeal/member/service/MemberServiceTest.java
- 컨트롤러 테스트 및 테스트용 커스텀 애노테이션 추가 (d708cc87f8fa42bf90a3bd9ed60063a5e6c77dbf)
> 컨트롤러 테스트 및 애노테이션 추가

- src/main/java/com/windmeal/chat/domain/ChatroomDocument.java
- src/main/java/com/windmeal/chat/dto/request/ChatRoomSaveRequest.java
- 채팅방 도큐먼트에 오너, 게스트의 이메일 추가 (85f5d94f77ed1aed9947d8d17a28dce56fe0aab0)
> 채팅방 도큐먼트 필드 추가, 관련 로직 수정

- src/main/java/com/windmeal/order/controller/DeliveryController.java
- src/main/java/com/windmeal/order/controller/OrderController.java
- src/main/java/com/windmeal/store/controller/MenuController.java
- 제네릭이 명시되지 않아 Swagger에 타입이 표시되지 않은 항목들 모두 수정 (40ebe4a97eceae908637ab87a7f9caea78ea70c9)
> 스웨거 제네릭 명시

- src/main/java/com/windmeal/order/dto/response/DeliveryListResponse.java
- src/main/java/com/windmeal/order/repository/delivery/DeliveryCustomRepositoryImpl.java
- src/main/java/com/windmeal/order/service/DeliveryService.java
- 내가 배달중인 목록 API 반환값 및 Query 수정 (d08a3741a5f804ff2bb3dfb6ceef3342cfc8911d)
- 배달원이 출발한 음식점의 이름 추가
> Refactor : 내가 배달중인 목록 누락된 데이터 추가

- src/main/java/com/windmeal/order/dto/response/OrderingListResponse.java
- src/main/java/com/windmeal/order/repository/delivery/DeliveryCustomRepositoryImpl.java
- 내가 배달중인 목록 API 반환값 및 Query 수정 (3839d50aed6837c117ca8f7cd40cf226294ba19b)
- 배달원이 출발한 음식점과 이름 추가
> 내가 주문한 목록 누락된 데이터 추가

- src/main/java/com/windmeal/order/dto/response/OrderDetailResponse.java
- src/main/java/com/windmeal/order/service/OrderService.java
- 주문 내역 상세 조회 API 응답값 추가
- 음식점 (출발지) 명 추가
> 주문 내역 상세 조회 API 응답값 추가

- src/main/java/com/windmeal/chat/service/ChatRoomService.java
- src/test/java/com/windmeal/chatroom/service/ChatroomServiceTest.java
- 채팅방 서비스 테스트 (c362bc75130b332defeb020febdd4df4261b3be5, 2d9c1b89a4cd50d25325612488a5203c9d8aac23)
- 채팅방 생성 조건 수정 (12c02375e2054e632b16dc83012af5507df248ab)
- 취소된 주문도 채팅방 생성 허용
> 채팅방 서비스 테스트

- src/main/java/com/windmeal/global/constants/S3Constant.java
- 기본 이미지 값 변경 (c78c84d296d6705d745ff6e3d305cbfd4286ef4d)
- 공통 처리를 위한 디렉토리 추가
> 기본 이미지 값 변경

- src/main/java/com/windmeal/global/util/TimeUtil.java
- src/main/java/com/windmeal/store/repository/StoreCustomRepositoryImpl.java
ex)
- 인스턴스에서 LocalTime의 인스턴스가 한국의 시간과 다른 문제 발생.
- TimeUtil 클래스 생성하여 한국 시간으로 변경하는 로직 추가 (936ea389f379d205d82cae6ea3a059607e043f58)
> 인스턴스 시간대 일치를 위한 TimeUtil 추가

- src/main/java/com/windmeal/global/util/TimeUtil.java
- src/main/java/com/windmeal/store/repository/StoreCustomRepositoryImpl.java
- 현재 시간 받아오는 코드 TimeUtil로 처리 (e8a91b062af9512d33dba09dfaf7e162a1ec12a1)
> 인스턴스 시간대 일치를 위한 TimeUtil 로직 수정

- src/main/java/com/windmeal/store/repository/StoreCustomRepositoryImpl.java
- 시간 관련 코드 원상복구
- 인스턴스의 타임 존을 수정해서 이슈를 해결하기로 계획 변경
> 시간 관련 코드 원상복구, 인스턴스 타임존 수정 예정

- src/main/java/com/windmeal/order/dto/request/OrderCreateRequest.java
- src/main/java/com/windmeal/store/repository/StoreCustomRepositoryImpl.java
- 프론트 요구사항 반영 (5e4aec52c008f30a817b895ef9c8cd9c82895989)
- 주문 생성 DTO 수정
- queryDSL 코드 수정
> Fix : 프론트 요구사항 반영

- src/main/java/com/windmeal/store/service/StoreService.java
- 가게 위치명 중복 불가능 설정 (412f5283631b92c893bc1dd8e4e6c29093773eab)
> 가게 장소명 중복 관련 로직 수정

- src/main/java/com/windmeal/global/S3/S3Util.java
- 프론트엔드의 요구로 인한 가게 기본 이미지명 변경 (718cb71037c31c26dbfd1d1eefdbc7abc109456a)
> 가게 기본 이미지 텍스트 변경

- src/main/java/com/windmeal/global/configuration/security/SecurityConfig.java
- src/main/java/com/windmeal/member/service/AuthService.java
- 방화벽 정책 변경, 보안 위협 코드 제거 (9e156b832d4fddaa616c24843803dfa16f6a7b03)
- URL 특정 문자 허용
- 사용자 관련 정보 확인용 로그 제거
> 방화벽 정책 변경, 보안 위협 코드 제거

- src/main/java/com/windmeal/global/configuration/WebConfig.java
> Fix : 방화벽 정책 변경

- src/main/java/com/windmeal/global/configuration/WebConfig.java
> 방화벽 정책 변경 - 허용 오리진 수정

- src/main/java/com/windmeal/global/security/impl/filter/CustomCorsFilter.java
> cors 필터 수정 - 복수 오리진 허용

- src/main/java/com/windmeal/global/configuration/security/SecurityConfig.java
- 비로그인 사용자 허용 api 목록 수정
- /store/* 경로에 대해서 GET 메서드 모두 허용
> 비로그인 사용자 허용 api 목록 수정

- src/main/java/com/windmeal/global/configuration/security/SecurityConfig.java
- corsFilter 수정
- wildcard 사용 실수 수정
> corsFilter 수정

- src/main/java/com/windmeal/order/controller/OrderController.java
- src/main/java/com/windmeal/order/dto/response/OrderDetailResponse.java
- 주문 상세 조회 api 필드 추가
- 주문 요약 정보 추가
> 주문 상세 조회 api 요약 정보 추가

- src/main/java/com/windmeal/global/configuration/security/SecurityConfig.java
> 주문 조회 api 비회원 허용

- src/main/java/com/windmeal/order/controller/DeliveryController.java
- src/main/java/com/windmeal/order/domain/Delivery.java
- src/main/java/com/windmeal/order/dto/request/DeliveryCompleteRequest.java
- src/main/java/com/windmeal/order/exception/InvalidDeliverException.java
- src/main/java/com/windmeal/order/exception/NotProcessingDeliveryException.java
- src/main/java/com/windmeal/order/service/DeliveryService.java
> 배달 완료 api 추가

- src/main/java/com/windmeal/global/constants/SecurityConstants.java
- src/main/java/com/windmeal/global/security/handler/CustomSuccessHandler.java
- 리다이렉트 uri 배포 주소로 수정
- 기존 로컬 주소에서 배포 주소로 수정됨
> Fix : 리다이렉트 uri 배포 주소로 수정

- src/main/java/com/windmeal/order/dto/response/OwnDeliveryListResponse.java
- src/main/java/com/windmeal/order/dto/response/OwnOrderListResponse.java
- 내가 주문한 / 배달한 목록 오류 수정
- 필드 추가로 인한 생성자 오류가 발생
- 모두 수정 후 테스트 완료
> 내가 주문/배달한 목록 생성자 오류 수정

- src/main/java/com/windmeal/order/domain/Delivery.java
- src/main/java/com/windmeal/order/service/DeliveryService.java
> 배달 완료 관련 로직 수정

- src/main/java/com/windmeal/order/dto/response/OrderDetailResponse.java
> 주문 세부 조회 필드 추가

- src/main/java/com/windmeal/global/security/impl/filter/JwtAuthenticationFilter.java
- src/main/java/com/windmeal/global/util/AES256Util.java
- 프론트엔드측 2중 암호화 추가
- jwt 토큰 관련 보안 강화를 위함
> 프론트엔드측 2중 암호화 추가

- src/main/java/com/windmeal/global/security/impl/filter/JwtAuthenticationFilter.java
> Refactor : 디버깅용 로그 추가

- src/main/java/com/windmeal/global/security/impl/filter/JwtAuthenticationFilter.java
- src/main/java/com/windmeal/global/util/AES256Util.java
- 원인 식별
- 프론트엔드 키 복호화와 백엔드 키 복호화의 순서가 잘못돼서 발생했던 오류였음.
- 조치
- 순서 변경
> 원인 식별, 조치 및 디버깅용 로그 삭제

- src/main/java/com/windmeal/global/util/AES256Util.java
> Refactor : 최종 확인용 로그 추가

- src/main/java/com/windmeal/member/service/AuthService.java
> Refactor : Reissue 암/복호화 부분 수정

- src/main/java/com/windmeal/global/constants/JwtConstants.java
- src/main/java/com/windmeal/global/security/impl/filter/JwtAuthenticationFilter.java
- src/main/java/com/windmeal/global/util/AES256Util.java
- 보안상 민감한 로그 제거
- 테스트를 위한 토큰 유효시간 수정
> Refactor : 보안상 민감한 로그 제거, 테스트를 위한 토큰 유효시간 수정

- src/main/java/com/windmeal/global/constants/JwtConstants.java
- src/main/java/com/windmeal/order/service/OrderService.java
- 토큰 유효시간 복구
- 수익 관련 로직 수정
- 부호가 반대로 설정되어야 함 (1500원 이득 -> -1500으로 표기됨)
> Refactor : 토큰 유효시간 복구 및 수익 관련 로직 수정

- src/main/java/com/windmeal/order/dto/response/DeliveryListResponse.java
- src/main/java/com/windmeal/order/dto/response/OrderDetailResponse.java
- src/main/java/com/windmeal/order/dto/response/OrderingListResponse.java
- src/main/java/com/windmeal/order/repository/delivery/DeliveryCustomRepositoryImpl.java
- src/main/java/com/windmeal/order/service/OrderService.java
- 프론트엔드 요구사항 반영
- 특정 api 응답값에 대해 상대방의 프로필 이미지 표시를 위한 필드 추가
> 프론트엔드 요구사항 반영

- src/main/java/com/windmeal/order/repository/delivery/DeliveryCustomRepositoryImpl.java
- 프론트엔드 요구사항 반영 관련 쿼리 오류 수정
- QueryDSL의 Projection의 타입에 Tuple이 있었는데, 생성자에는 Tuple이 없어서 오류 발생
- 조인으로 변경한 후 필드 각각을 추가해줌
> 프론트엔드 요구사항 반영 관련 쿼리 오류 수정

- src/main/java/com/windmeal/global/constants/S3Constant.java
- src/main/java/com/windmeal/global/security/oauth2/impl/CustomOAuth2UserService.java
- 회원가입 시 사용자의 프로필 사진을 랜덤으로 생성하도록 기능 수정
> 프론트엔드 요구사항 반영 - 랜덤 프로필 사진

- src/main/java/com/windmeal/member/controller/BlackListController.java
- src/main/java/com/windmeal/member/service/BlackListService.java
- 사용자 차단 API 작성
- BlackListController 생성, Swagger 코드 추가
- 기존 작성되어 있던 Service 로직
> 사용자 차단 API 작성

- src/main/java/com/windmeal/member/controller/MemberReportController.java
- src/main/java/com/windmeal/member/dto/request/MemberReportCreateRequest.java
- src/main/java/com/windmeal/member/service/MemberReportService.java
- 사용자 신고 API 리팩토링
- 신고자 ID 관련 불필요 로직 및 필드 제거
- 불필요 필드 (신고 제목) 제거
> 사용자 신고 API 요구사항 반영

- src/main/java/com/windmeal/member/dto/request/MemberReportCreateRequest.java
- 사용자 신고 API 관련 빌드 오류 원인 수정
- DTO에서 제거한 필드로 엔티티의 생성자를 구성하는 코드 존재
- 프론트엔드와 소통 후 우선 빌드 오류 해결을 위해 오류 부분 롤백
> 사용자 신고 API 관련 빌드 오류 원인 수정

- src/main/java/com/windmeal/member/dto/request/BlackListCreateRequest.java
- src/main/java/com/windmeal/member/service/BlackListService.java
- 사용자 차단 DTO필드 수정
- 기존 이메일에서 아이디로 수정
> 사용자 차단 DTO 필드 수정

- src/main/java/com/windmeal/order/controller/OrderController.java
- src/main/java/com/windmeal/order/domain/Order.java
- src/main/java/com/windmeal/order/dto/request/DeliveryFeeUpdateRequest.java
- src/main/java/com/windmeal/order/service/OrderService.java
> 배달료 수정 api 작성

- src/main/java/com/windmeal/generic/domain/Money.java
- src/main/java/com/windmeal/order/controller/OrderController.java
- src/main/java/com/windmeal/order/service/OrderService.java
- 배달료 수정 요청 DTO 수정
- Money 객체 형태의 요청을 Integer로 변경
- 로직 수정
- 애노테이션 누락 실수 수정 -> 애노테이션 추가
> 배달료 수정 요청 DTO 및 로직 수정

- src/main/java/com/windmeal/member/controller/MemberController.java
- src/main/java/com/windmeal/member/dto/response/MyPageDTO.java
- src/main/java/com/windmeal/member/service/MemberService.java
- 프론트의 요청사항으로 인해 마이페이지 응답 필드 추가
> 마이페이지 응답 필드 추가

- src/main/java/com/windmeal/global/security/oauth2/impl/CustomOAuth2UserService.java
- src/main/java/com/windmeal/member/controller/MemberController.java
- src/main/java/com/windmeal/member/domain/Member.java
- src/main/java/com/windmeal/member/domain/MemberBase.java
- src/main/java/com/windmeal/member/dto/request/MemberAccountDeleteRequest.java
- src/main/java/com/windmeal/member/exception/MemberNotMatchException.java
- src/main/java/com/windmeal/member/service/MemberService.java
- 회원탈퇴 api 추가
- 학과명 양식 변경
- 앞단의 슬래쉬 제거
> 회원탈퇴 api, 학과명 양식 변경

- src/main/java/com/windmeal/global/configuration/security/SecurityConfig.java
- src/main/java/com/windmeal/member/service/MemberService.java
- 메뉴 옵션 조회 api 권한 수정
- 기존 권한은 인증된 사용자만 실행 가능
- 변경된 권한은 모든 사용자에 대해 실행 가능
> 메뉴 옵션 조회 api 권한 public으로 수정

- src/main/java/com/windmeal/chat/controller/ChatRoomController.java
- src/main/java/com/windmeal/chat/dto/response/ChatRoomExistsResponse.java
- src/main/java/com/windmeal/chat/repository/ChatroomDocumentRepository.java
- src/main/java/com/windmeal/chat/service/ChatRoomService.java
> 채팅방 존재 유무 확인 API 추가

- src/main/java/com/windmeal/chat/service/ChatRoomService.java
- nullPointerException 발생 부분 수정
> 채팅방 존재 유무 확인 - null 처리 수정
